---
services:
  main:
    build:
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      NG_ALLOWED_HOSTS: 'localhost'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules/

volumes:
  node_modules:
