import { EmbeddedRenderDto } from './dtos';

export const EMBEDDED_VIEWS = [
  {
    id: 'free-consulting',
    name: 'Reunión de contexto',
    renderHtmlBase64:
      'PCEtLSBDYWwgaW5saW5lIGVtYmVkIGNvZGUgYmVnaW5zIC0tPgo8ZGl2IHN0eWxlPSJ3aWR0aDoxMDAlO2hlaWdodDoxMDAlO292ZXJmbG93OnNjcm9sbCIgaWQ9Im15LWNhbC1pbmxpbmUtcmV1bmlvbi1kZS1jb250ZXh0byI+PC9kaXY+CjxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0Ij4KICAoZnVuY3Rpb24gKEMsIEEsIEwpIHsgbGV0IHAgPSBmdW5jdGlvbiAoYSwgYXIpIHsgYS5xLnB1c2goYXIpOyB9OyBsZXQgZCA9IEMuZG9jdW1lbnQ7IEMuQ2FsID0gQy5DYWwgfHwgZnVuY3Rpb24gKCkgeyBsZXQgY2FsID0gQy5DYWw7IGxldCBhciA9IGFyZ3VtZW50czsgaWYgKCFjYWwubG9hZGVkKSB7IGNhbC5ucyA9IHt9OyBjYWwucSA9IGNhbC5xIHx8IFtdOyBkLmhlYWQuYXBwZW5kQ2hpbGQoZC5jcmVhdGVFbGVtZW50KCJzY3JpcHQiKSkuc3JjID0gQTsgY2FsLmxvYWRlZCA9IHRydWU7IH0gaWYgKGFyWzBdID09PSBMKSB7IGNvbnN0IGFwaSA9IGZ1bmN0aW9uICgpIHsgcChhcGksIGFyZ3VtZW50cyk7IH07IGNvbnN0IG5hbWVzcGFjZSA9IGFyWzFdOyBhcGkucSA9IGFwaS5xIHx8IFtdOyBpZih0eXBlb2YgbmFtZXNwYWNlID09PSAic3RyaW5nIil7Y2FsLm5zW25hbWVzcGFjZV0gPSBjYWwubnNbbmFtZXNwYWNlXSB8fCBhcGk7cChjYWwubnNbbmFtZXNwYWNlXSwgYXIpO3AoY2FsLCBbImluaXROYW1lc3BhY2UiLCBuYW1lc3BhY2VdKTt9IGVsc2UgcChjYWwsIGFyKTsgcmV0dXJuO30gcChjYWwsIGFyKTsgfTsgfSkod2luZG93LCAiaHR0cHM6Ly9hcHAuY2FsLmNvbS9lbWJlZC9lbWJlZC5qcyIsICJpbml0Iik7CkNhbCgiaW5pdCIsICJyZXVuaW9uLWRlLWNvbnRleHRvIiwge29yaWdpbjoiaHR0cHM6Ly9hcHAuY2FsLmNvbSJ9KTsKCiAgQ2FsLm5zWyJyZXVuaW9uLWRlLWNvbnRleHRvIl0oImlubGluZSIsIHsKICAgIGVsZW1lbnRPclNlbGVjdG9yOiIjbXktY2FsLWlubGluZS1yZXVuaW9uLWRlLWNvbnRleHRvIiwKICAgIGNvbmZpZzogeyJsYXlvdXQiOiJtb250aF92aWV3IiwidGhlbWUiOiJsaWdodCJ9LAogICAgY2FsTGluazogImxlY3VhbGFiL3JldW5pb24tZGUtY29udGV4dG8iLAogIH0pOwoKICBDYWwubnNbInJldW5pb24tZGUtY29udGV4dG8iXSgidWkiLCB7InRoZW1lIjoibGlnaHQiLCJjc3NWYXJzUGVyVGhlbWUiOnsibGlnaHQiOnsiY2FsLWJyYW5kIjoiIzE5OTM5QSJ9LCJkYXJrIjp7ImNhbC1icmFuZCI6IiNGMjhCMzEifX0sImhpZGVFdmVudFR5cGVEZXRhaWxzIjpmYWxzZSwibGF5b3V0IjoibW9udGhfdmlldyJ9KTsKICA8L3NjcmlwdD4KICA8IS0tIENhbCBpbmxpbmUgZW1iZWQgY29kZSBlbmRzIC0tPg==',
    description:
      'Transformemos tu marca con poder. Elige el día y hora que más te acomode.',
    keywords: [
      'agendar diagnóstico diseño gráfico empresarial',
      'consulta gratuita agencia de branding',
      'agendar asesoría en diseño corporativo',
      'reunión de evaluación para branding empresarial',
      'reserva de hora con estudio de diseño gráfico',
      'diagnóstico visual gratuito para empresas',
      'agendar llamada con agencia de diseño estratégico',
      'branding gratuito primera reunión',
    ],
  },
] as const satisfies readonly EmbeddedRenderDto[];
